name: voice_message_package
description: Flutter package to play/puase voice message in chat messengers.
version: 1.0.31
homepage: https://github.com/mehranshoqi/voice_message_player

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.0
  just_audio: ^0.9.35
  syncfusion_flutter_sliders: ^23.1.39

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


